name: Meu primeiro Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Executando job teste
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Step 1
        run: echo "Primeiro Step"

      - name: Step 2
        run: echo "Segundo Step"
