name: Meu primeiro Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Executando job teste
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'rafaelload'
          password: ${{ secrets.SECRETE }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
           context: .
           tags: 'latest'
           push: true 
                
