name: Meu primeiro Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Executando job teste
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: 'rafaelload'
          password: ${{ secrets.SECRETE }}
          
